global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul:1.9.4
  metrics:
    enabled: true
    enableAgentMetrics: true
  imageEnvoy: envoyproxy/envoy:v1.16.4
server:
  replicas: 1
ui:
  enabled: true
connectInject:
  enabled: true
  default: true
controller:
  enabled: true
prometheus:
  enabled: true
grafana:
  enabled: true
